name: TestCache

on:
  push:
    branches:
    - main
    - add-workflows
    - dev
  pull_request:
    branches:
    - main
    - add-workflows
    - dev

jobs:
  test_caches:
    runs-on: ubuntu-22.04
    container: 
      image: docker.io/ujenetort/lfu_cache:latest
    steps:

    - name: checkout
      uses: actions/checkout@v4
    
    - name: build
      run: |
        ./build.sh
        cd build
      shell: bash
    
    - name: test_lfu_hits
      run: ./test --gtest_filter=TestLFU.hits
      working-directory: build
      shell: bash

    - name: test_lfu_stress
      run: ./test --gtest_filter=TestLFU.stress
      working-directory: build
      shell: bash

    - name: test_belady_hits
      run: ./test --gtest_filter=TestBelady.hits
      working-directory: build
      shell: bash

    - name: test_belady_stress
      run: ./test --gtest_filter=TestBelady.stress
      working-directory: build
      shell: bash

    - name: test_compare
      run: ./test --gtest_filter=CompareCaches.lfu_less_hits_than_ideal
      working-directory: build
      shell: bash
