name: TestCache

on:
  push:
    branches:
    - main
    - add-workflows
    - dev
  pull_request:
    branches:
    - main
    - add-workflows
    - dev

jobs:
  test_caches:
    runs-on: ubuntu-22.04
    steps:

    - name: install-dependencies
      run: |
        sudo apt update
        sudo apt install cmake ninja-build build-essential libgtest-dev podman
      shell: bash

    - name: checkout
      uses: actions/checkout@v4
    
    - name: build podman container 
      run: |
        podman build . -t lfu_cache:latest
    
    - name: run podman container 
      run: |
        podman run lfu_cache:latest --mount type=bind,src=./, dst=/root/app
        cd build 
      shell: bash
    
#   - name: configure
#     run: |
#       mkdir -p build && cd build
#       cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
#     shell: bash

#   - name: build
#     run:  ninja
#     working-directory: build
#     shell: bash

    - name: test_lfu_hits
      run: ./test --gtest_filter=TestLFU.hits
      working-directory: build
      shell: bash

    - name: test_lfu_stress
      run: ./test --gtest_filter=TestLFU.stress
      working-directory: build
      shell: bash

    - name: test_belady_hits
      run: ./test --gtest_filter=TestBelady.hits
      working-directory: build
      shell: bash

    - name: test_belady_stress
      run: ./test --gtest_filter=TestBelady.stress
      working-directory: build
      shell: bash

    - name: test_compare
      run: ./test --gtest_filter=CompareCaches.lfu_less_hits_than_ideal
      working-directory: build
      shell: bash
